### ISSUE TITLE
documentar y simplificar código

### ISSUE THREAD

**Issue by Gambled23** [Gambled23/TheNishaProject#42]
Documentar los algoritmos de php
simplificar los blade, tenemos mucho blade y pocos componentes/layouts, no c si podamos reestructurar esa madre
El código llegó a un punto en el q está demasiado potente y tenemos como 4 comentarios explicando xddd

**Comment by cybness** [comment]
los estilos y todo lo de las vistas son problemas para la aranza del futuro, ahorita pura funcionalidad
