### ISSUE TITLE
Validación para cuando no tienes tags en la BD

### ISSUE THREAD

**Issue by Gambled23** [Gambled23/TheNishaProject#46]
Si se intenta agregar un producto sin tags, dará error al intentar recuperarlas
![image](https://github.com/Gambled23/TheNishaProject/assets/58153130/d751b938-016d-4d1d-a3ba-49f128becf8d)

**Comment by cybness** [comment]
if mi mejor amigo 
![image](https://github.com/Gambled23/TheNishaProject/assets/94998372/28d55f37-049c-41a4-83e3-c624bfb7fa0b)
