### ISSUE TITLE
informar en formulario create y edit si los campos de tiempo no tienen datos

### ISSUE THREAD

**Issue by Gambled23** [Gambled23/TheNishaProject#47]
![image](https://github.com/Gambled23/TheNishaProject/assets/58153130/69cfc450-13e9-4239-b6c3-14e5bbb6c354)

**Comment by cybness** [comment]
No sé porque no funciona el required, odiomuchoelvalidate.

**Comment by cybness** [comment]
odio inmensamente el hecho de que esto era funcional con el código que hay en este momento.
