### ISSUE TITLE
Botones de index producto

### ISSUE THREAD

**Issue by Gambled23** [Gambled23/TheNishaProject#48]
por qué un botón está más arriba por qué se cree superior aquí todos valemos lo mismo
![image](https://github.com/Gambled23/TheNishaProject/assets/58153130/8af4aa1b-d8de-41de-9eb3-5c5a1c3a9777)

**Comment by cybness** [comment]
jakdn a mi no me salen azules, ni se nota que está más arriba.
![image](https://github.com/Gambled23/TheNishaProject/assets/94998372/507f7af8-0204-440b-9347-8571d1cf4cc0)

**Comment by Gambled23** [comment]
Mi mayor enemigos los bugs que no pasan siempre

**Comment by Gambled23** [comment]
era por el modo oscuro jeje
