### ISSUE TITLE
Hacer soft delete de eliminar cuenta

### ISSUE THREAD

**Issue by Gambled23** [Gambled23/TheNishaProject#6]

**Comment by cybness** [comment]
- [ ] archive

**Comment by cybness** [comment]
- [ ] Arreglar login (solo deja login con third party)

**Comment by cybness** [comment]
- [ ] is trashed (no sé en donde) para que no me de el fastidioso error de que ya hay usuarios repetidos, tmb algun error display en pantalla funcionaría

**Comment by Gambled23** [comment]
> * [x]  Arreglar login (solo deja login con third party)

se me olvidó que había quitado el botón jej prdon ya lo volví a meter
